version: 2
jobs:
  build:
    working_directory: ~repo
    working_directory: ~/npm-lint
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
            - npm-lint-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-lint-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run:
          name: Build
          command: npm run build:client:prod
      - run:
          name: do-pack
          command: npm pack

workflows:
  version: 2
  build_and_activate:
    jobs:
      - build